# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-23 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_index', models.SmallIntegerField()),
                ('words', models.CharField(max_length=300)),
                ('frequency', models.SmallIntegerField()),
            ],
        ),
    ]
